config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'blog/index'

  resources :posts do
    resources :comments
  end

  root :to => "blog#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :post

  default_scope {order('created_at DESC')}

end

app/models/post.rb
class Post < ApplicationRecord

  validates :name,  :presence => true
  validates :title, :presence => true,
            :length => { :minimum => 20 }

  has_many :comments, :dependent => :destroy

  has_many :tags
  accepts_nested_attributes_for :tags, :allow_destroy => :true,
                                :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

  default_scope {order('created_at DESC')}

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_action :set_post, only: [:show]

  # GET /posts
  # GET /posts.json
  def index
    @blog = Post.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:name, :title, :content)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(params.require(:comment).permit!)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post), :notice => 'Comment was deleted'
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new, :create, :destroy, :edit, :update]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.paginate(page: params[:page], per_page: 20)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def join_tags(post)
    post.tags.map { |t| t.name }.join(", ")
  end
end

app/views/blog/index.html.erb
<!-- Home Posts -->
<section class="home-posts">
  <div class="row">
    <h1>Ze světa frontendu</h1>
    <p>Tipy, triky, články, návody.</p>
  </div>
</section>
<!-- Cancel Home Posts -->

<!-- Posts -->
<section class="posts">
  <div class="row">

    <% @blog.each do |post| %>
        <!-- Panel -->
        <div class="small-6 large-6 columns">
          <!-- Article -->
          <article class="article">
            <div class="post">
              <h2><%= post.name %></h2>
              <p>
                <small><%= post.created_at.to_s(:short) %></small>
              </p>
              <p>
                <%= post.title %>
              </p>

              <p>
                <%= link_to 'Detail', post %>
              </p>
            </div>
          </article><!-- Cancel Article -->
        </div><!-- Cancel Panel -->
    <% end %>

    <div class="small-12 large-12 columns">
      <%= will_paginate @posts %>
    </div>
  </div>
</section>
<!-- Cancel Posts -->

app/views/comments/_comment.html.erb
<p>
  <%= comment.created_at.to_s(:short) %> Author - <strong><%= comment.commenter %></strong>
  <br>
  <q><%= comment.body %></q>
</p>

<p>
  <%= link_to 'Delete comment', [comment.post, comment],
              :confirm => 'Are you sure?',
              :method => :delete %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <div class="field form-control-static">
      <%= f.label :author %><br />
      <%= f.text_field :commenter %>
    </div>
    <div class="field form-control-static-textarea">
      <%= f.label :comment %><br />
      <%= f.text_area :body %>
    </div>
    <div class="actions btn-new-comment">
      <%= f.submit %>
    </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="main-menu">
  <div class="row">
    <div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle></button>
      <div class="title-bar-title">Menu</div>
    </div>

    <div class="top-bar" id="example-menu">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <li id="logo"><%= link_to "DPNPD", root_path %></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu menu__ul menu__mainMenu">
          <% if user_signed_in? %>

              <li class="menu__item menu__href"><%= link_to "Administration", posts_path %></li>
              <li class="menu__item menu__href"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>

          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title></title>
    <meta name="description" content="">
    <meta name="author" content="Petr Nikolas Prokop">
    <link rel="shortcut icon" href="favicon.ico?v=3">

    <meta property="og:title" content="">
    <meta property="og:description" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <meta property="og:type" content="website">
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= stylesheet_link_tag params[:controller] %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <main>
      <%= yield %>
    </main>

    <footer>
      <div class="row">
        <p>
          <a href="http://petrnikolas.cz">&copy; DPNPD</a>
        </p>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/foundation/6.2.3/foundation.min.js"></script>
    <script>
      $(document).foundation();
    </script>
    <script type="text/javascript" src="https://intercom.zurb.com/scripts/zcom.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
  </body>
</html>

app/views/posts/_form.html.erb
<% @post.tags.build %>
<%= form_for(@post) do |post_form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-control-static">
    <%= post_form.label :name %>
    <%= post_form.text_field :name %>
  </div>

  <div class="field form-control-static">
    <%= render :partial => 'tags/form',
               :locals => {:form => post_form} %>
  </div>

  <div class="field form-control-static">
    <%= post_form.label :title %>
    <%= post_form.text_field :title %>
  </div>

  <div class="field form-control-static-textarea">
    <%= post_form.label :content %>
    <%= post_form.text_area :content %>
  </div>

  <div class="actions btn btn-default">
    <%= post_form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<!-- Home Blog -->
<section class="home-posts">
  <div class="row">
      <h1>Editing Post</h1>
  </div>
</section>
<!-- Cancel Home Blog -->

<!-- Posts -->
<section class="posts">
  <div class="row">
      <article>
        <%= render 'form', post: @post %>

        <hr>
        <p>
          <%= link_to 'Detail', @post %>
          |
          <%= link_to 'Back', posts_path %>
        </p>
      </article>
  </div>
</section>
<!-- Cancel Posts -->

app/views/posts/index.html.erb
<!-- Home Posts -->
<section class="home-posts">
  <div class="row">
      <h1>Blog's administration</h1>
  </div>
</section>
<!-- Cancel Home Posts -->

<!-- Posts -->
<section class="posts">
  <div class="row center">
    <p id="notice"><%= notice %></p>

    <div class="small-4 large-4 columns">
      <div class="admin-nav">
        <p>
          <i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;
          <%= Time.now %>
        </p>

        <div class="actions btn btn-new">
          <p>
            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>&nbsp;
            <%= link_to 'New post', new_post_path %>
          </p>
        </div>

        <p>
          <a class="twitter-timeline" href="https://twitter.com/PetrNikolas" data-chrome="nofooter noheader" data-tweet-limit="3"></a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
        </p>
      </div>
    </div>

    <div class="small-8 large-8 columns">
      <div class="row">
        <% @posts.each do |post| %>
            <!-- Panel -->
              <div class="small-4 large-4 columns">
                <!-- Article -->
                <article class="article">
                  <div class="post">
                    <h2><%= post.name %></h2>
                    <p>
                      <small><%= post.created_at.to_s(:short) %></small>
                    </p>

                    <p>
                      <%= link_to 'Detail', post %>
                      |
                      <%= link_to 'Edit', edit_post_path(post) %>
                      |
                      <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </p>
                  </div>
                </article><!-- Cancel Article -->
              </div><!-- Cancel Panel -->
        <% end %>
      </div>

      <div class="small-12 large-12 columns">
        <%= will_paginate @posts %>
      </div>
    </div>
  </div>
</section>
<!-- Cancel Posts -->

app/views/posts/new.html.erb
<!-- Home Posts -->
<section class="home-posts">
  <div class="row">
      <h1>New Post</h1>
  </div>
</section>
<!-- Cancel Home Posts -->

<!-- Posts -->
<section class="posts">
  <div class="row">
      <article>
        <%= render 'form', post: @post %>

        <br>
        <p>
          <%= link_to 'Back', posts_path %>
        </p>
      </article>
  </div>
</section>
<!-- Cancel Posts -->

app/views/posts/show.html.erb
<!-- Home Posts -->
<section class="home-posts">
  <div class="row">
    <h1>
      <%= @post.name %>
    </h1>
    <p>
      <small><%= join_tags(@post) %></small>
    </p>

  </div>
</section>
<!-- Cancel Home Posts -->

<div class="row">
  <div class="small-12 large-12 columns">
    <!-- Posts -->
    <section class="posts">
        <article>
          <p>
            <%= @post.content %>
          </p>
        </article>
    </section>
    <!-- Cancel Posts -->
  </div>

  <div class="small-12 large-12 columns">
    <section class="posts">
      <p>

        <% if user_signed_in? %>

            <%= link_to 'Edit', edit_post_path(@post) %>
            |
            <%= link_to 'Back', posts_path %>

        <% else %>

            <%= link_to 'Zpět', blog_index_path %>

        <% end %>
      </p>
    </section>
  </div>
</div>

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
    <div class="field form-control-static">
      <%= tag_form.label :name, 'Tag' %>
      <%= tag_form.text_field :name %>
    </div>
    <% unless tag_form.object.nil? || tag_form.object.new_record? %>
        <div class="field form-control-static">
          <%= tag_form.label :_destroy, 'Remove:' %>
          <%= tag_form.check_box :_destroy %>
        </div>
    <% end %>
<% end %>